name: Continuous Integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: for dir in ./p[0-9][0-9][0-9]; do (cd "$dir" && cargo test); done
